// javascript/todo-list-sql/client/src/views/Login.jsx
import { Button, Card, Container, Row, Col, Input } from "reactstrap";
import React, { useState, useEffect, useRef } from "react";
import { User } from "@genezio-sdk/todo-list";
import { useNavigate } from "react-router-dom";

export default (props) => {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  async function handleSubmit(event) {
    event.preventDefault();
    if (!email || !password) {
      setError("All fields are mandatory");
      return;
    }

    setError("");

    const res = await User.login(email, password);

    if (!res.success) {
      if (res.err) {
        setError(res.err);
      } else {
        if (res.msg) {
          setError(res.msg);
        } else {
          setError(
            "Unexpected Error:Please check the backend logs in the project dashboard - https://app.genez.io. ",
          );
        }
      }

      return;
    } else {
      localStorage.setItem("apiToken", res.token);
      localStorage.setItem("user", JSON.stringify(res.user));
      navigate("/admin/all-tasks");
    }
  }

  return (
    <Container className="mt-5">
      <Row className="mt-5">
        <Col sm="12" md={{ size: 6, offset: 3 }}>
          <Card className="p-4 mt-5">
            <div className="auth-wrapper">
              <div className="auth-inner">
                <form>
                  <h3>Sign In</h3>
                  <span className="text-danger">{error}</span>
                  <div className="mb-3">
                    <label>Email address</label>
                    <Input
                      className="form-control"
                      placeholder="Email"
                      type="email"
                      autoComplete="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                    />
                  </div>
                  <div className="mb-3">
                    <label>Password</label>
                    <Input
                      className="form-control"
                      placeholder="Password"
                      type="password"
                      autoComplete="password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                    />
                  </div>
                  <div className="text-left">
                    <Button
                      type="submit"
                      color="primary"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Submit
                    </Button>
                  </div>
                  <div className="mt-2">
                    <span>
                      Don't have an account? <a href="/register">Register</a>
                    </span>
                  </div>
                </form>
              </div>
            </div>
          </Card>
        </Col>
      </Row>
    </Container>
  );
};

// typescript/todo-list-angular/client/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth/auth.service';
import { UserLoginResponse } from '@genezio-sdk/todo-list-ts';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  authFailed: boolean = false;
  authFailedMsg?: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  submitLogin(email: string, password: string) {
    if (!email || !password) {
      this.authFailed = true;
      this.authFailedMsg = 'All fields are mandatory';
      return;
    }

    this.authService
      .auth(email, password)
      .then((response: UserLoginResponse) => {
        if (!response.success) {
          this.authFailed = true;
          if (response.msg) {
            this.authFailedMsg = response.msg;
          } else {
            if (response.err) {
              this.authFailedMsg = 'Unexpected error: ' + response.err;
            } else {
              this.authFailedMsg =
                'Unexpected error: Please check the backend logs in the project dashboard - https://app.genez.io.';
            }
          }
          return;
        }

        this.router.navigate(['']);
      });
  }
}

<div class="col-sm-12 col-md-6 offset-md-3">
    <div class="p-4 mt-5 card">
        <form>
            <h3>Sign In</h3>
            <ngb-alert type="danger" *ngIf="authFailed">{{authFailedMsg}}</ngb-alert>
            <div class="mb-3">
                <label>Email address</label>
                <input placeholder="Email" #email autocomplete="email" type="email" class="form-control form-control" value="">
            </div>
            
            <div class="mb-3">
                <label>Password</label>
                <input placeholder="Password" #password autocomplete="password" type="password" class="form-control form-control" value="">
            </div>
            
            <div class="text-left">
                <button type='button' class="btn btn-primary" (click)="submitLogin(email.value, password.value)">Submit</button>
            </div>

            <div class="mt-2">   
                <span>Don't have an account? <a routerLink="/register">Register</a></span>
            </div>
        </form>
    </div>
</div>
