// typescript/todo-list-auth-mongo/client/src/views/AllTasks.tsx
import {
  Button,
  Card,
  Container,
  Row,
  Col,
  Input,
  Modal,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ButtonGroup,
  Alert,
} from "reactstrap";
import { useState, useEffect } from "react";
import {
  TaskService,
  Task,
  GetTasksResponse,
} from "@genezio-sdk/todo-list-auth-mongo";
import { useNavigate } from "react-router-dom";
import { AuthService } from "@genezio/auth";

export default function AllTasks() {
  const navigate = useNavigate();

  const [tasks, setTasks] = useState<Task[]>([]);
  const [modalAddTask, setModalAddTask] = useState(false);
  const toggleModalAddTask = () => {
    setModalAddTask(!modalAddTask);
    setTaskTitle("");
  };

  const [error, setError] = useState("");
  const [alertErrorMessage, setAlertErrorMessage] = useState<string>("");

  const [taskTitle, setTaskTitle] = useState("");

  useEffect(() => {
    TaskService.getAllTasksByUser().then((result: GetTasksResponse) => {
      if (result.success) {
        setTasks(result.tasks);
      } else {
        if (result.err) {
          setAlertErrorMessage(
            `Unexpected error: ${
              result.err
                ? result.err
                : "Please check the backend logs in the project dashboard - https://app.genez.io."
            }`
          );
        }
      }
    });
  }, []);

  async function handleDelete(id: string) {
    const res = await TaskService.deleteTask(id);
    if (res.success) {
      navigate(0);
    } else {
      navigate(0);
      setAlertErrorMessage(
        `Unexpected error: ${
          res.err
            ? res.err
            : "Please check the backend logs in the project dashboard - https://app.genez.io."
        }`
      );
    }
  }

  async function handleEdit(id: string, title: string, solved: boolean) {
    const res = await TaskService.updateTask(id, title, solved);
    if (res.success) {
      const newTasks = tasks.map((task) => {
        if (task._id === id) {
          task.title = title;
          task.solved = solved;
        }
        return task;
      });
      setTasks(newTasks);
    } else {
      setAlertErrorMessage(
        `Unexpected error: ${
          res.err
            ? res.err
            : "Please check the backend logs in the project dashboard - https://app.genez.io."
        }`
      );
    }
  }

  async function handleAdd(e: React.MouseEvent<HTMLButtonElement>) {
    e.preventDefault();
    if (!taskTitle) {
      setError("Title is mandatory");
      return;
    }
    const res = await TaskService.createTask(taskTitle);
    if (res.success) {
      setTasks([...tasks, res.task!]);
      setTaskTitle("");
      toggleModalAddTask();
    } else {
      setAlertErrorMessage(
        `Unexpected error: ${
          res.err
            ? res.err
            : "Please check the backend logs in the project dashboard - https://app.genez.io."
        }`
      );
    }
  }

  return alertErrorMessage != "" ? (
    <Row className="ms-5 me-5 ps-5 pe-5 mt-5 pt-5">
      <Alert color="danger">{alertErrorMessage}</Alert>
    </Row>
  ) : (
    <>
      <Modal isOpen={modalAddTask} toggle={toggleModalAddTask}>
        <ModalHeader toggle={toggleModalAddTask}>Add new task</ModalHeader>
        <form>
          <ModalBody>
            <span className="text-danger">{error}</span>
            <div className="mb-3">
              <label>Task Title</label>
              <Input
                className="form-control"
                placeholder="Title"
                autoComplete="Title"
                value={taskTitle}
                onChange={(e) => setTaskTitle(e.target.value)}
              />
            </div>
          </ModalBody>
          <ModalFooter>
            <Button color="primary" onClick={(e) => handleAdd(e)} type="submit">
              Add
            </Button>
            <Button color="secondary" onClick={toggleModalAddTask}>
              Cancel
            </Button>
          </ModalFooter>
        </form>
      </Modal>
      <Container className="mt-2">
        <Card className="p-4 mt-2">
          <Row className="mt-2">
            <Col sm="11">
              <h3>All Tasks</h3>

              <Row>
                <Col sm="12">
                  {tasks.map((task) => (
                    <div key={task._id} className="mb-3">
                      <p className="mb-0">
                        <span className="h4">{task.title}</span> -{" "}
                        {task.solved ? "Solved" : "Not Solved"}
                      </p>
                      <ButtonGroup aria-label="Basic example">
                        <Button
                          color="danger"
                          onClick={() => handleDelete(task._id)}
                        >
                          Delete Task
                        </Button>
                        <Button
                          color="primary"
                          onClick={() =>
                            handleEdit(task._id, task.title, !task.solved)
                          }
                        >
                          {task.solved ? "Mark as Unsolved" : "Mark as Solved"}
                        </Button>
                      </ButtonGroup>
                    </div>
                  ))}
                </Col>

                <Col sm="3" className="mt-4">
                  <Button
                    color="primary"
                    onClick={() => {
                      toggleModalAddTask();
                    }}
                  >
                    Add Task
                  </Button>
                </Col>
              </Row>
            </Col>
            <Col sm="1" className="text-right">
              <Button
                color="primary"
                onClick={async () => {
                  await AuthService.getInstance().logout();
                  navigate("/auth/login");
                }}
              >
                Logout
              </Button>
            </Col>
          </Row>
        </Card>
      </Container>
    </>
  );
}

// typescript/todo-list-angular/client/src/app/components/all-tasks/all-tasks.component.ts
import { Component } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { AuthService } from 'src/app/services/auth/auth.service';
import { TasksService } from 'src/app/services/tasks/tasks.service';
import { Task } from '@genezio-sdk/todo-list-ts';

@Component({
  selector: 'app-all-tasks',
  templateUrl: './all-tasks.component.html',
  styleUrls: ['./all-tasks.component.css'],
})
export class AllTasksComponent {
  allTasks: Task[] = [];
  dbError: String = '';

  constructor(
    private modalService: NgbModal,
    private tasksService: TasksService,
    private authService: AuthService
  ) {}

  ngOnInit() {
    this.tasksService.error$.subscribe((error: any) => {
      this.dbError = error;
    });
    this.tasksService.getTasks().then((res) => {
      if (res.success) {
        this.allTasks = res.tasks;
      } else {
        if (res.err) {
          this.tasksService.setError(res.err);
        } else {
          this.tasksService.setError(
            'Unexpected error: Please check the backend logs in the project dashboard - https://app.genez.io.'
          );
        }
      }
    });
  }

  openModal(content: any) {
    this.modalService
      .open(content, { ariaLabelledBy: 'modal-basic-title' })
      .result.then((result) => {
        if (!result) {
          return;
        }

        this.tasksService.createTask(result).then((res) => {
          if (res.success) {
            this.allTasks.push(res.task!);
          } else {
            if (res.err) {
              this.tasksService.setError(res.err);
            } else {
              this.tasksService.setError(
                'Unexpected error: Please check the backend logs in the project dashboard - https://app.genez.io.'
              );
            }
          }
        });
      });
  }

  taskDeleted(id: string) {
    this.allTasks = this.allTasks.filter(function (task) {
      return task._id !== id;
    });
  }

  logout() {
    this.authService.logout();
  }
}

<ng-template #content let-modal>
	<div class="modal-header">
		<h4 class="modal-title" id="modal-basic-title">Add new task</h4>
		<button type="button" class="btn-close" aria-label="Close" (click)="modal.dismiss('closeBtn')"></button>
	</div>
	<div class="modal-body">
        <div class="mb-3">
            <label for="taskTitle">Task title</label>
            <div class="input-group">
                <input
                    #taskTitle
                    type="text"
                    class="form-control"
                    placeholder="Title"
                    name="taskTitle"
                />
            </div>
        </div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-outline-dark" (click)="modal.close(taskTitle.value)">Save</button>
	</div>
</ng-template>

<div class="p-4 mt-2 card">
    <div class="mt-2 row">
        <div class="col-sm-11">
            <ngb-alert type="danger" *ngIf="dbError">{{dbError}}</ngb-alert>
            <h3>All Tasks</h3>
            <div class="row">
                <app-task *ngFor="let task of allTasks" [title]='task.title' [id]="task._id" [solved]="task.solved" (onDelete)="taskDeleted(task._id)"></app-task>

                <div class="mt-4 col-sm-3">
                    <button type="button" class="btn btn-primary" (click)="openModal(content)">Add Task</button>
                </div>
            </div>
        </div>

        <div class="text-right col-sm-1">
            <button type="button" class="btn btn-primary" (click)="logout()">Logout</button>
        </div>
    </div>
</div>
