// typescript/todo-list-angular/client/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { RegisterService } from 'src/app/services/register/register.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent {
  registerFailed: boolean = false;
  registerFailedMsg?: string = '';

  constructor(
    private registerService: RegisterService,
    private router: Router
  ) {}

  submitRegister(name: string, email: string, password: string) {
    if (!name || !email || !password) {
      this.registerFailed = true;
      this.registerFailedMsg = 'All fields are mandatory';
      return;
    }

    this.registerService.register(name, email, password).then((res) => {
      if (!res.success) {
        this.registerFailed = true;
        if (res.msg) {
          this.registerFailedMsg = res.msg;
        } else {
          if (res.err) {
            this.registerFailedMsg = 'Unexpected error: ' + res.err;
          } else {
            this.registerFailedMsg =
              'Unexpected error: Please check the backend logs in the project dashboard - https://app.genez.io.';
          }
        }
        return;
      }

      this.router.navigate(['login']);
    });
  }
}

<div class="col-sm-12 col-md-6 offset-md-3">
    <div class="p-4 mt-5 card">
        <form>
            <h3>Register</h3>
            <ngb-alert type="danger" *ngIf="registerFailed">{{registerFailedMsg}}</ngb-alert>

            <div class="mb-3">
                <label>Name</label>
                <input placeholder="Name" #name autocomplete="name" type="text" class="form-control form-control" value="">
            </div>

            <div class="mb-3">
                <label>Email address</label>
                <input placeholder="Email" #email autocomplete="email" type="email" class="form-control form-control" value="">
            </div>
            
            <div class="mb-3">
                <label>Password</label>
                <input placeholder="Password" #password autocomplete="password" type="password" class="form-control form-control" value="">
            </div>
            
            <div class="text-left">
                <button type='button' class="btn btn-primary" (click)="submitRegister(name.value, email.value, password.value)">Submit</button>
            </div>

            <div class="mt-2">   
                <span>Already have an account? <a routerLink="/login">Login</a></span>
            </div>
        </form>
    </div>
</div>

// javascript/todo-list-sql/client/src/views/Register.jsx
import { Button, Card, Container, Row, Col, Input } from "reactstrap";
import React, { useState } from "react";
import { User } from "@genezio-sdk/todo-list";
import { useNavigate } from "react-router-dom";

export default (props) => {
  const navigate = useNavigate();

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [password2, setPassword2] = useState("");

  const [error, setError] = useState("");

  async function handleSubmit(event) {
    event.preventDefault();
    if (!email || !password || !password2 || !name) {
      setError("All fields are mandatory");
      return;
    }
    if (password !== password2) {
      setError("Passwords do not match");
      return;
    }

    setError("");

    const res = await User.register(name, email, password);
    setError("res", res);

    if (!res.success) {
      if (res.err) {
        setError(res.err);
      } else {
        if (res.msg) {
          setError(res.msg);
        } else {
          setError(
            "Unexpected Error:Please check the backend logs in the project dashboard - https://app.genez.io. ",
          );
        }
      }

      return;
    } else {
      navigate("/login");
    }
  }

  return (
    <Container className="mt-5">
      <Row className="mt-5">
        <Col sm="12" md={{ size: 6, offset: 3 }}>
          <Card className="p-4 mt-5">
            <div className="auth-wrapper">
              <div className="auth-inner">
                <form>
                  <h3>Sign Up</h3>
                  <span className="text-danger">{error}</span>
                  <div className="mb-3">
                    <label>Name</label>
                    <Input
                      className="form-control"
                      placeholder="Name"
                      type="name"
                      autoComplete="name"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                    />
                  </div>
                  <div className="mb-3">
                    <label>Email address</label>
                    <Input
                      className="form-control"
                      placeholder="Email"
                      type="email"
                      autoComplete="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                    />
                  </div>
                  <div className="mb-3">
                    <label>Password</label>
                    <Input
                      className="form-control"
                      placeholder="Password"
                      type="password"
                      autoComplete="password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                    />
                  </div>
                  <div className="mb-3">
                    <label>Password</label>
                    <Input
                      className="form-control"
                      placeholder="Repeat Password"
                      type="password"
                      value={password2}
                      onChange={(e) => setPassword2(e.target.value)}
                    />
                  </div>
                  <div className="text-left">
                    <Button
                      type="submit"
                      color="primary"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Submit
                    </Button>
                  </div>
                  <div className="mt-2">
                    <span>
                      Already have an account? <a href="/login">Login</a>
                    </span>
                  </div>
                </form>
              </div>
            </div>
          </Card>
        </Col>
      </Row>
    </Container>
  );
};
