// golang/chatgpt-project/client/src/App.tsx
import { For, createSignal } from "solid-js";

import { GptCaller } from "@genezio-sdk/chatgpt-project";

import "./App.css";

type Message = {
  text: string;
  isUser: boolean;
};

function App() {
  const [messages, setMessages] = createSignal<Message[]>([]);
  const [requestText, setRequestText] = createSignal("");
  const [isRequesting, setIsRequesting] = createSignal(false);

  const [alertError, setAlertError] = createSignal("");

  function sendRequest(e: Event) {
    e.preventDefault();
    setIsRequesting(true);
    GptCaller.askChatGpt(requestText())
      .then((response) => {
        console.log(response);
        setMessages([
          ...messages(),
          { text: requestText(), isUser: true },
          { text: response, isUser: false },
        ]);
        setRequestText("");
        setIsRequesting(false);
      })
      .catch((error) => {
        console.error(error);
        setAlertError("An error occurred: " + error);
        setIsRequesting(false);
      });
  }

  return (
    <div class="App">
      <section class="msger">
        <header class="msger-header">
          <h4>Rephrasing app using ChatGPT, Genezio and React</h4>
        </header>

        {alertError() != "" ? (
          <main class="msger-chat">
            <div class="alert">{alertError()}</div>
          </main>
        ) : (
          <main class="msger-chat">
            <For each={messages()}>
              {(message) => {
                if (message.isUser) {
                  return (
                    <div class="msg right-msg">
                      <div class="msg-bubble">
                        <div class="msg-info">
                          <div class="msg-info-name">You</div>
                        </div>

                        <div class="msg-text">{message.text}</div>
                      </div>
                    </div>
                  );
                } else {
                  return (
                    <div class="msg left-msg">
                      <div class="msg-bubble">
                        <div class="msg-info">
                          <div class="msg-info-name">ChatGPT</div>
                        </div>

                        <div class="msg-text">{message.text}</div>
                      </div>
                    </div>
                  );
                }
              }}
            </For>
          </main>
        )}

        <form class="msger-inputarea" onSubmit={(e) => sendRequest(e)}>
          <input
            type="text"
            class="msger-input"
            placeholder="Enter your message..."
            value={requestText()}
            onChange={(e) => setRequestText(e.target.value)}
          />
          <button
            type="submit"
            class="msger-send-btn"
            onClick={(e) => sendRequest(e)}
          >
            {isRequesting() ? "Sending..." : "Send"}
          </button>
        </form>
      </section>
    </div>
  );
}

export default App;

// javascript/chatgpt-project/client/src/App.jsx
import { useState } from "react";
import { GptCaller } from "@genezio-sdk/chatgpt-project";
import "./App.css";

function App() {
    // each mesage format: {text: "message", isUser: true/false}
    const [messages, setMessages] = useState([]);
    const [requestText, setRequestText] = useState("");
    const [isRequesting, setIsRequesting] = useState(false);

    const [alertError, setAlertError] = useState("");

    function sendRequest(e) {
        e.preventDefault();
        setIsRequesting(true);
        GptCaller.askChatGPT(requestText)
            .then((response) => {
                if (!response.success) {
                    setAlertError(
                        `Unexpected error: ${response.err
                            ? response.err
                            : "Please check the backend logs in the project dashboard - https://app.genez.io."
                        }`,
                    );
                    return;
                }
                setMessages([
                    {
                        text: requestText,
                        isUser: true,
                    },
                    {
                        text: response.content,
                        isUser: false,
                    },
                ]);
                setRequestText("");
                setIsRequesting(false);
            })
            .catch((err) => {
                console.log(err);
                setIsRequesting(false);
            });
    }

    return (
        <div className="App">
            <section className="msger">
                <header className="msger-header">
                    <h4>Rephrasing app using ChatGPT, Genezio and React</h4>
                </header>

                {alertError != "" ? (
                    <main className="msger-chat">
                        <div className="alert">{alertError}</div>
                    </main>
                ) : (
                    <main className="msger-chat">
                        {messages.map((message, index) => {
                            if (message.isUser) {
                                return (
                                    <div className="msg right-msg" key={index}>
                                        <div className="msg-bubble">
                                            <div className="msg-info">
                                                <div className="msg-info-name">You</div>
                                            </div>

                                            <div className="msg-text">{message.text}</div>
                                        </div>
                                    </div>
                                );
                            } else {
                                return (
                                    <div className="msg left-msg" key={index}>
                                        <div className="msg-bubble">
                                            <div className="msg-info">
                                                <div className="msg-info-name">ChatGPT</div>
                                            </div>

                                            <div className="msg-text">{message.text}</div>
                                        </div>
                                    </div>
                                );
                            }
                        })}
                    </main>
                )}

                <form className="msger-inputarea" onSubmit={(e) => sendRequest(e)}>
                    <input
                        type="text"
                        className="msger-input"
                        placeholder="Enter your message..."
                        value={requestText}
                        onChange={(e) => setRequestText(e.target.value)}
                    />
                    <button
                        type="submit"
                        className="msger-send-btn"
                        onClick={(e) => sendRequest(e)}
                    >
                        {isRequesting ? "Sending..." : "Send"}
                    </button>
                </form>
            </section>
        </div>
    );
}

export default App;
